# -*- coding: utf-8 -*-
"""AIS_Project_C1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rzbQ8EclMWWv0efKkxdhHSm1aJcfqoCO
"""

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 2.x

! pip install git+https://github.com/divamgupta/image-segmentation-keras

!mkdir /content/dataset
!mkdir /content/dataset/train_images
!mkdir /content/dataset/train_segmentation
!mkdir /content/dataset/val_images
!mkdir /content/dataset/val_segmentation

from PIL import Image

for i in range(147):
  i = i+1
  img = Image.open('/content/drive/MyDrive/Json-Files/Segmentation/'+str(i)+'.png').convert('LA')
  img.save('/content/drive/MyDrive/Json-Files/Segmentation_greyscale/'+str(i)+'.png')

from keras_segmentation.models.unet import vgg_unet
from keras_segmentation.models.fcn import fcn_32_vgg

#model = vgg_unet(n_classes=129 ,  input_height=384, input_width=384)

model = fcn_32_vgg(n_classes =129, input_height = 384, input_width =384)

model.train(
    train_images =  "/content/drive/MyDrive/Json-Files/Images",
    train_annotations = "/content/drive/MyDrive/Json-Files/Segmentation_greyscale",
    checkpoints_path = "/tmp/vgg_unet_1" , epochs=6
)

from keras_segmentation.data_utils.data_loader import class_colors
print(class_colors)
print(model.summary)

out = model.predict_segmentation(
    inp="/content/drive/MyDrive/Big_Dataset_Test_Images/IMG_3402.png",
    out_fname="/tmp/out.png"
)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import matplotlib
import matplotlib.pyplot as plt

plt.imshow(out)

from IPython.display import Image
Image('/tmp/out.png')

o = model.predict_segmentation(
    inp="/content/drive/MyDrive/Big_Dataset_Test_Images/IMG_3402.png",
    out_fname="/tmp/out.png" , overlay_img=True, show_legends=True,
    class_names = [ "_background_","Can","Mug","Spoon","Knife", "Plate", "Bonbon" , "Foodbar" , "Handkerchief", "Pen", "Ball", "Banana", "iPad" , "Mask" , "Fork", "Scissor", "Calculator", "Toothpaste", "Toothbrush", "Toiletpaper", "Bottle" , "Milk"]
    #class_names = ["_background_", "bottle", "can"]
)

from IPython.display import Image
Image('/tmp/out.png')

"""Quelle : https://divamgupta.com/image-segmentation/2019/06/06/deep-learning-semantic-segmentation-keras.html"""